/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClaimCreate
 */
export interface ClaimCreate {
    /**
     * Internal claim status
     * @type {string}
     * @memberof ClaimCreate
     */
    status: ClaimCreateStatusEnum;
    /**
     * Internal claim type
     * @type {string}
     * @memberof ClaimCreate
     */
    type?: string;
    /**
     * What is our role on this claim
     * @type {string}
     * @memberof ClaimCreate
     */
    participation?: string;
    /**
     * The loss or event name associated with the claim
     * @type {string}
     * @memberof ClaimCreate
     */
    lossOrEventName: string;
    /**
     * Claims cause of loss
     * @type {string}
     * @memberof ClaimCreate
     */
    causeOfLoss?: string;
    /**
     * Location where the loss event occurred
     * @type {string}
     * @memberof ClaimCreate
     */
    lossLocation?: string;
    /**
     * Name of the vessel associated with the claim
     * @type {string}
     * @memberof ClaimCreate
     */
    vesselName?: string;
    /**
     * Internal Policy ID for reference back to Policy API
     * @type {string}
     * @memberof ClaimCreate
     */
    policyId: string;
    /**
     * Internal friendly claim reference
     * @type {string}
     * @memberof ClaimCreate
     */
    insurerReference?: string;
    /**
     * ECF -> UCR
     * @type {string}
     * @memberof ClaimCreate
     */
    brokerClaimReference?: string;
    /**
     * ECF -> UMR
     * @type {string}
     * @memberof ClaimCreate
     */
    brokerPolicyReference: string | null;
    /**
     * Risk code associated with the claim
     * @type {string}
     * @memberof ClaimCreate
     */
    riskCode?: string;
    /**
     * Class of business associated with the claim
     * @type {string}
     * @memberof ClaimCreate
     */
    classOfBusiness?: string;
    /**
     * Underwriting year associated with the claim
     * @type {string}
     * @memberof ClaimCreate
     */
    underwritingYear?: string;
    /**
     * Date received first notice of loss
     * @type {Date}
     * @memberof ClaimCreate
     */
    fnolDate?: Date;
    /**
     * Date of the loss event
     * @type {Date}
     * @memberof ClaimCreate
     */
    lossDate?: Date;
    /**
     * Date the claim was closed
     * @type {Date}
     * @memberof ClaimCreate
     */
    closeDate?: Date;
}


/**
 * @export
 */
export const ClaimCreateStatusEnum = {
    FirstNoticeOfLoss: 'first_notice_of_loss',
    Hold: 'hold',
    WaitingSurveyor: 'waiting_surveyor',
    OngoingInvestigation: 'ongoing_investigation',
    AwaitingDocs: 'awaiting_docs',
    NoCollaboration: 'no_collaboration',
    WaitingInvestigationReport: 'waiting_investigation_report',
    CoverageReview: 'coverage_review',
    LegalReview: 'legal_review',
    ReferredDenial: 'referred_denial',
    DenialIssued: 'denial_issued',
    Settlement: 'settlement',
    WaitingVendorBilling: 'waiting_vendor_billing',
    Recovery: 'recovery',
    ClosedPaid: 'closed_paid',
    ClosedDenied: 'closed_denied',
    ClosedWithdrawn: 'closed_withdrawn'
} as const;
export type ClaimCreateStatusEnum = typeof ClaimCreateStatusEnum[keyof typeof ClaimCreateStatusEnum];


/**
 * Check if a given object implements the ClaimCreate interface.
 */
export function instanceOfClaimCreate(value: object): boolean {
    if (!('status' in value)) return false;
    if (!('lossOrEventName' in value)) return false;
    if (!('policyId' in value)) return false;
    if (!('brokerPolicyReference' in value)) return false;
    return true;
}

export function ClaimCreateFromJSON(json: any): ClaimCreate {
    return ClaimCreateFromJSONTyped(json, false);
}

export function ClaimCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'type': json['type'] == null ? undefined : json['type'],
        'participation': json['participation'] == null ? undefined : json['participation'],
        'lossOrEventName': json['loss_or_event_name'],
        'causeOfLoss': json['cause_of_loss'] == null ? undefined : json['cause_of_loss'],
        'lossLocation': json['loss_location'] == null ? undefined : json['loss_location'],
        'vesselName': json['vessel_name'] == null ? undefined : json['vessel_name'],
        'policyId': json['policy_id'],
        'insurerReference': json['insurer_reference'] == null ? undefined : json['insurer_reference'],
        'brokerClaimReference': json['broker_claim_reference'] == null ? undefined : json['broker_claim_reference'],
        'brokerPolicyReference': json['broker_policy_reference'],
        'riskCode': json['risk_code'] == null ? undefined : json['risk_code'],
        'classOfBusiness': json['class_of_business'] == null ? undefined : json['class_of_business'],
        'underwritingYear': json['underwriting_year'] == null ? undefined : json['underwriting_year'],
        'fnolDate': json['fnol_date'] == null ? undefined : (new Date(json['fnol_date'])),
        'lossDate': json['loss_date'] == null ? undefined : (new Date(json['loss_date'])),
        'closeDate': json['close_date'] == null ? undefined : (new Date(json['close_date'])),
    };
}

export function ClaimCreateToJSON(value?: ClaimCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'type': value['type'],
        'participation': value['participation'],
        'loss_or_event_name': value['lossOrEventName'],
        'cause_of_loss': value['causeOfLoss'],
        'loss_location': value['lossLocation'],
        'vessel_name': value['vesselName'],
        'policy_id': value['policyId'],
        'insurer_reference': value['insurerReference'],
        'broker_claim_reference': value['brokerClaimReference'],
        'broker_policy_reference': value['brokerPolicyReference'],
        'risk_code': value['riskCode'],
        'class_of_business': value['classOfBusiness'],
        'underwriting_year': value['underwritingYear'],
        'fnol_date': value['fnolDate'] == null ? undefined : ((value['fnolDate'] as any).toISOString()),
        'loss_date': value['lossDate'] == null ? undefined : ((value['lossDate'] as any).toISOString()),
        'close_date': value['closeDate'] == null ? undefined : ((value['closeDate'] as any).toISOString()),
    };
}

