/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClaimMovementAmountItemCreate
 */
export interface ClaimMovementAmountItemCreate {
    /**
     * Type of amount item
     * @type {string}
     * @memberof ClaimMovementAmountItemCreate
     */
    type: string;
    /**
     * ISO 4217 currency code
     * @type {string}
     * @memberof ClaimMovementAmountItemCreate
     */
    amountCurrency: string;
    /**
     * Share amount
     * @type {string}
     * @memberof ClaimMovementAmountItemCreate
     */
    amountShare?: string;
    /**
     * Currency indicator
     * @type {string}
     * @memberof ClaimMovementAmountItemCreate
     */
    amountCurrencyIndicator?: string;
    /**
     * Amount value
     * @type {number}
     * @memberof ClaimMovementAmountItemCreate
     */
    amountValue: number;
}

/**
 * Check if a given object implements the ClaimMovementAmountItemCreate interface.
 */
export function instanceOfClaimMovementAmountItemCreate(value: object): boolean {
    if (!('type' in value)) return false;
    if (!('amountCurrency' in value)) return false;
    if (!('amountValue' in value)) return false;
    return true;
}

export function ClaimMovementAmountItemCreateFromJSON(json: any): ClaimMovementAmountItemCreate {
    return ClaimMovementAmountItemCreateFromJSONTyped(json, false);
}

export function ClaimMovementAmountItemCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimMovementAmountItemCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'amountCurrency': json['amount_currency'],
        'amountShare': json['amount_share'] == null ? undefined : json['amount_share'],
        'amountCurrencyIndicator': json['amount_currency_indicator'] == null ? undefined : json['amount_currency_indicator'],
        'amountValue': json['amount_value'],
    };
}

export function ClaimMovementAmountItemCreateToJSON(value?: ClaimMovementAmountItemCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'amount_currency': value['amountCurrency'],
        'amount_share': value['amountShare'],
        'amount_currency_indicator': value['amountCurrencyIndicator'],
        'amount_value': value['amountValue'],
    };
}

