/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a transaction-to-transaction (TR-to-TR) relationship within a linked claim
 * @export
 * @interface ClaimTransactionLinkedEntry
 */
export interface ClaimTransactionLinkedEntry {
    /**
     * Unique identifier for the linked entry
     * @type {string}
     * @memberof ClaimTransactionLinkedEntry
     */
    id: string;
    /**
     * ID of the linked claim this entry belongs to
     * @type {string}
     * @memberof ClaimTransactionLinkedEntry
     */
    linkedClaimId: string;
    /**
     * Transaction Reference (TR) of the linked transaction
     * @type {string}
     * @memberof ClaimTransactionLinkedEntry
     */
    linkedTr: string;
    /**
     * When the linked entry was created
     * @type {Date}
     * @memberof ClaimTransactionLinkedEntry
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the ClaimTransactionLinkedEntry interface.
 */
export function instanceOfClaimTransactionLinkedEntry(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('linkedClaimId' in value)) return false;
    if (!('linkedTr' in value)) return false;
    if (!('createdAt' in value)) return false;
    return true;
}

export function ClaimTransactionLinkedEntryFromJSON(json: any): ClaimTransactionLinkedEntry {
    return ClaimTransactionLinkedEntryFromJSONTyped(json, false);
}

export function ClaimTransactionLinkedEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimTransactionLinkedEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'linkedClaimId': json['linked_claim_id'],
        'linkedTr': json['linked_tr'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function ClaimTransactionLinkedEntryToJSON(value?: ClaimTransactionLinkedEntry | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'linked_claim_id': value['linkedClaimId'],
        'linked_tr': value['linkedTr'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

