/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Comment associated with an ECF claim transaction, supporting broker, private, public, and cross-market visibility levels
 * @export
 * @interface ClaimTransactionComment
 */
export interface ClaimTransactionComment {
    /**
     * Unique identifier for the comment
     * @type {string}
     * @memberof ClaimTransactionComment
     */
    id: string;
    /**
     * ID of the transaction this comment belongs to
     * @type {string}
     * @memberof ClaimTransactionComment
     */
    transactionId: string;
    /**
     * Type of comment determining visibility and limits
     * @type {string}
     * @memberof ClaimTransactionComment
     */
    commentType: ClaimTransactionCommentCommentTypeEnum;
    /**
     * Line number for ordering comments of the same type
     * @type {number}
     * @memberof ClaimTransactionComment
     */
    lineNumber: number;
    /**
     * The actual comment text (max 70 characters per ECF spec)
     * @type {string}
     * @memberof ClaimTransactionComment
     */
    commentDetails: string;
    /**
     * Additional metadata or cross-market comment data
     * @type {{ [key: string]: any; }}
     * @memberof ClaimTransactionComment
     */
    additionalInformation?: { [key: string]: any; };
    /**
     * When the comment was created
     * @type {Date}
     * @memberof ClaimTransactionComment
     */
    createdAt: Date;
}


/**
 * @export
 */
export const ClaimTransactionCommentCommentTypeEnum = {
    Broker: 'broker',
    Private: 'private',
    Public: 'public',
    CrossMarket: 'cross_market'
} as const;
export type ClaimTransactionCommentCommentTypeEnum = typeof ClaimTransactionCommentCommentTypeEnum[keyof typeof ClaimTransactionCommentCommentTypeEnum];


/**
 * Check if a given object implements the ClaimTransactionComment interface.
 */
export function instanceOfClaimTransactionComment(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('transactionId' in value)) return false;
    if (!('commentType' in value)) return false;
    if (!('lineNumber' in value)) return false;
    if (!('commentDetails' in value)) return false;
    if (!('createdAt' in value)) return false;
    return true;
}

export function ClaimTransactionCommentFromJSON(json: any): ClaimTransactionComment {
    return ClaimTransactionCommentFromJSONTyped(json, false);
}

export function ClaimTransactionCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimTransactionComment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'transactionId': json['transaction_id'],
        'commentType': json['comment_type'],
        'lineNumber': json['line_number'],
        'commentDetails': json['comment_details'],
        'additionalInformation': json['additional_information'] == null ? undefined : json['additional_information'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function ClaimTransactionCommentToJSON(value?: ClaimTransactionComment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'transaction_id': value['transactionId'],
        'comment_type': value['commentType'],
        'line_number': value['lineNumber'],
        'comment_details': value['commentDetails'],
        'additional_information': value['additionalInformation'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

