/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClaimTransactionFinancialUpdate
 */
export interface ClaimTransactionFinancialUpdate {
    /**
     * ISO 4217 currency code
     * @type {string}
     * @memberof ClaimTransactionFinancialUpdate
     */
    currency: string;
    /**
     * Service provider original split references
     * @type {Array<string>}
     * @memberof ClaimTransactionFinancialUpdate
     */
    serviceProviderOriginalSplitReference?: Array<string>;
    /**
     * Settlement amount in the specified currency
     * @type {number}
     * @memberof ClaimTransactionFinancialUpdate
     */
    settlementAmount?: number;
    /**
     * Exchange rate for currency conversion
     * @type {number}
     * @memberof ClaimTransactionFinancialUpdate
     */
    exchangeRate?: number;
    /**
     * Target currency for exchange rate conversion (ISO 4217)
     * @type {string}
     * @memberof ClaimTransactionFinancialUpdate
     */
    targetCurrency?: string;
}

/**
 * Check if a given object implements the ClaimTransactionFinancialUpdate interface.
 */
export function instanceOfClaimTransactionFinancialUpdate(value: object): boolean {
    if (!('currency' in value)) return false;
    return true;
}

export function ClaimTransactionFinancialUpdateFromJSON(json: any): ClaimTransactionFinancialUpdate {
    return ClaimTransactionFinancialUpdateFromJSONTyped(json, false);
}

export function ClaimTransactionFinancialUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimTransactionFinancialUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'serviceProviderOriginalSplitReference': json['service_provider_original_split_reference'] == null ? undefined : json['service_provider_original_split_reference'],
        'settlementAmount': json['settlement_amount'] == null ? undefined : json['settlement_amount'],
        'exchangeRate': json['exchange_rate'] == null ? undefined : json['exchange_rate'],
        'targetCurrency': json['target_currency'] == null ? undefined : json['target_currency'],
    };
}

export function ClaimTransactionFinancialUpdateToJSON(value?: ClaimTransactionFinancialUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'currency': value['currency'],
        'service_provider_original_split_reference': value['serviceProviderOriginalSplitReference'],
        'settlement_amount': value['settlementAmount'],
        'exchange_rate': value['exchangeRate'],
        'target_currency': value['targetCurrency'],
    };
}

