/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClaimMovementAmountItemCreate } from './ClaimMovementAmountItemCreate';
import {
    ClaimMovementAmountItemCreateFromJSON,
    ClaimMovementAmountItemCreateFromJSONTyped,
    ClaimMovementAmountItemCreateToJSON,
} from './ClaimMovementAmountItemCreate';

/**
 * 
 * @export
 * @interface ClaimTransactionFinancialCreate
 */
export interface ClaimTransactionFinancialCreate {
    /**
     * ISO 4217 currency code
     * @type {string}
     * @memberof ClaimTransactionFinancialCreate
     */
    currency: string;
    /**
     * Service provider original split references
     * @type {Array<string>}
     * @memberof ClaimTransactionFinancialCreate
     */
    serviceProviderOriginalSplitReference?: Array<string>;
    /**
     * Settlement amount in the specified currency
     * @type {number}
     * @memberof ClaimTransactionFinancialCreate
     */
    settlementAmount?: number;
    /**
     * Exchange rate for currency conversion
     * @type {number}
     * @memberof ClaimTransactionFinancialCreate
     */
    exchangeRate?: number;
    /**
     * Target currency for exchange rate conversion (ISO 4217)
     * @type {string}
     * @memberof ClaimTransactionFinancialCreate
     */
    targetCurrency?: string;
    /**
     * Amount items breakdown for this financial record
     * @type {Array<ClaimMovementAmountItemCreate>}
     * @memberof ClaimTransactionFinancialCreate
     */
    amountItems?: Array<ClaimMovementAmountItemCreate>;
}

/**
 * Check if a given object implements the ClaimTransactionFinancialCreate interface.
 */
export function instanceOfClaimTransactionFinancialCreate(value: object): boolean {
    if (!('currency' in value)) return false;
    return true;
}

export function ClaimTransactionFinancialCreateFromJSON(json: any): ClaimTransactionFinancialCreate {
    return ClaimTransactionFinancialCreateFromJSONTyped(json, false);
}

export function ClaimTransactionFinancialCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimTransactionFinancialCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'serviceProviderOriginalSplitReference': json['service_provider_original_split_reference'] == null ? undefined : json['service_provider_original_split_reference'],
        'settlementAmount': json['settlement_amount'] == null ? undefined : json['settlement_amount'],
        'exchangeRate': json['exchange_rate'] == null ? undefined : json['exchange_rate'],
        'targetCurrency': json['target_currency'] == null ? undefined : json['target_currency'],
        'amountItems': json['amount_items'] == null ? undefined : ((json['amount_items'] as Array<any>).map(ClaimMovementAmountItemCreateFromJSON)),
    };
}

export function ClaimTransactionFinancialCreateToJSON(value?: ClaimTransactionFinancialCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'currency': value['currency'],
        'service_provider_original_split_reference': value['serviceProviderOriginalSplitReference'],
        'settlement_amount': value['settlementAmount'],
        'exchange_rate': value['exchangeRate'],
        'target_currency': value['targetCurrency'],
        'amount_items': value['amountItems'] == null ? undefined : ((value['amountItems'] as Array<any>).map(ClaimMovementAmountItemCreateToJSON)),
    };
}

