/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Claim } from './Claim';
import {
    ClaimFromJSON,
    ClaimFromJSONTyped,
    ClaimToJSON,
} from './Claim';
import type { ThirdPartyEntity } from './ThirdPartyEntity';
import {
    ThirdPartyEntityFromJSON,
    ThirdPartyEntityFromJSONTyped,
    ThirdPartyEntityToJSON,
} from './ThirdPartyEntity';

/**
 * 
 * @export
 * @interface ClaimsClaimIdWithEntitiesGet200Response
 */
export interface ClaimsClaimIdWithEntitiesGet200Response {
    /**
     * 
     * @type {Claim}
     * @memberof ClaimsClaimIdWithEntitiesGet200Response
     */
    claim: Claim;
    /**
     * 
     * @type {Array<ThirdPartyEntity>}
     * @memberof ClaimsClaimIdWithEntitiesGet200Response
     */
    thirdPartyEntities: Array<ThirdPartyEntity>;
}

/**
 * Check if a given object implements the ClaimsClaimIdWithEntitiesGet200Response interface.
 */
export function instanceOfClaimsClaimIdWithEntitiesGet200Response(value: object): boolean {
    if (!('claim' in value)) return false;
    if (!('thirdPartyEntities' in value)) return false;
    return true;
}

export function ClaimsClaimIdWithEntitiesGet200ResponseFromJSON(json: any): ClaimsClaimIdWithEntitiesGet200Response {
    return ClaimsClaimIdWithEntitiesGet200ResponseFromJSONTyped(json, false);
}

export function ClaimsClaimIdWithEntitiesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimsClaimIdWithEntitiesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'claim': ClaimFromJSON(json['claim']),
        'thirdPartyEntities': ((json['third_party_entities'] as Array<any>).map(ThirdPartyEntityFromJSON)),
    };
}

export function ClaimsClaimIdWithEntitiesGet200ResponseToJSON(value?: ClaimsClaimIdWithEntitiesGet200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'claim': ClaimToJSON(value['claim']),
        'third_party_entities': ((value['thirdPartyEntities'] as Array<any>).map(ThirdPartyEntityToJSON)),
    };
}

