/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClaimTransactionInsurerCreate } from './ClaimTransactionInsurerCreate';
import {
    ClaimTransactionInsurerCreateFromJSON,
    ClaimTransactionInsurerCreateFromJSONTyped,
    ClaimTransactionInsurerCreateToJSON,
} from './ClaimTransactionInsurerCreate';

/**
 * 
 * @export
 * @interface ClaimTransactionContractMarketCreate
 */
export interface ClaimTransactionContractMarketCreate {
    /**
     * Agency identifier
     * @type {string}
     * @memberof ClaimTransactionContractMarketCreate
     */
    agency: string;
    /**
     * List of insurers/reinsurers to create in this contract market
     * @type {Array<ClaimTransactionInsurerCreate>}
     * @memberof ClaimTransactionContractMarketCreate
     */
    insurers?: Array<ClaimTransactionInsurerCreate>;
}

/**
 * Check if a given object implements the ClaimTransactionContractMarketCreate interface.
 */
export function instanceOfClaimTransactionContractMarketCreate(value: object): boolean {
    if (!('agency' in value)) return false;
    return true;
}

export function ClaimTransactionContractMarketCreateFromJSON(json: any): ClaimTransactionContractMarketCreate {
    return ClaimTransactionContractMarketCreateFromJSONTyped(json, false);
}

export function ClaimTransactionContractMarketCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimTransactionContractMarketCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'agency': json['agency'],
        'insurers': json['insurers'] == null ? undefined : ((json['insurers'] as Array<any>).map(ClaimTransactionInsurerCreateFromJSON)),
    };
}

export function ClaimTransactionContractMarketCreateToJSON(value?: ClaimTransactionContractMarketCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'agency': value['agency'],
        'insurers': value['insurers'] == null ? undefined : ((value['insurers'] as Array<any>).map(ClaimTransactionInsurerCreateToJSON)),
    };
}

