/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClaimTransactionInsurerCreate
 */
export interface ClaimTransactionInsurerCreate {
    /**
     * Party agency identifier (e.g., 'lloyds')
     * @type {string}
     * @memberof ClaimTransactionInsurerCreate
     */
    partyAgency?: string;
    /**
     * Party ID text (e.g., 'urn:lloyds:1796')
     * @type {string}
     * @memberof ClaimTransactionInsurerCreate
     */
    partyId?: string;
    /**
     * Party name (e.g., 'SYNDICATE 3000')
     * @type {string}
     * @memberof ClaimTransactionInsurerCreate
     */
    partyName: string;
    /**
     * Contact person name
     * @type {string}
     * @memberof ClaimTransactionInsurerCreate
     */
    contactName?: string;
    /**
     * Contact telephone number
     * @type {string}
     * @memberof ClaimTransactionInsurerCreate
     */
    contactTelephone?: string;
    /**
     * Contact email address
     * @type {string}
     * @memberof ClaimTransactionInsurerCreate
     */
    contactEmail?: string;
    /**
     * Type of share percentage
     * @type {string}
     * @memberof ClaimTransactionInsurerCreate
     */
    sharePercentageType?: ClaimTransactionInsurerCreateSharePercentageTypeEnum;
    /**
     * Share percentage rate unit
     * @type {string}
     * @memberof ClaimTransactionInsurerCreate
     */
    sharePercentageRateUnit?: string;
    /**
     * Share percentage value
     * @type {number}
     * @memberof ClaimTransactionInsurerCreate
     */
    insurerSharePercentageValue?: number;
    /**
     * Insurer or reinsurer claim reference 1
     * @type {string}
     * @memberof ClaimTransactionInsurerCreate
     */
    insurerClaimReference1?: string;
    /**
     * Insurer or reinsurer claim reference 2
     * @type {string}
     * @memberof ClaimTransactionInsurerCreate
     */
    insurerClaimReference2?: string;
    /**
     * Participant function (Lead, Agreement Party, Follower)
     * @type {string}
     * @memberof ClaimTransactionInsurerCreate
     */
    participantFunction?: string;
    /**
     * Managing agent code
     * @type {string}
     * @memberof ClaimTransactionInsurerCreate
     */
    managingAgentCode?: string;
    /**
     * Consortium number
     * @type {string}
     * @memberof ClaimTransactionInsurerCreate
     */
    consortiumNumber?: string;
    /**
     * Claim line number
     * @type {number}
     * @memberof ClaimTransactionInsurerCreate
     */
    claimLineNumber?: number;
}


/**
 * @export
 */
export const ClaimTransactionInsurerCreateSharePercentageTypeEnum = {
    Insurer: 'insurer',
    Reinsurer: 'reinsurer'
} as const;
export type ClaimTransactionInsurerCreateSharePercentageTypeEnum = typeof ClaimTransactionInsurerCreateSharePercentageTypeEnum[keyof typeof ClaimTransactionInsurerCreateSharePercentageTypeEnum];


/**
 * Check if a given object implements the ClaimTransactionInsurerCreate interface.
 */
export function instanceOfClaimTransactionInsurerCreate(value: object): boolean {
    if (!('partyName' in value)) return false;
    return true;
}

export function ClaimTransactionInsurerCreateFromJSON(json: any): ClaimTransactionInsurerCreate {
    return ClaimTransactionInsurerCreateFromJSONTyped(json, false);
}

export function ClaimTransactionInsurerCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimTransactionInsurerCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'partyAgency': json['party_agency'] == null ? undefined : json['party_agency'],
        'partyId': json['party_id'] == null ? undefined : json['party_id'],
        'partyName': json['party_name'],
        'contactName': json['contact_name'] == null ? undefined : json['contact_name'],
        'contactTelephone': json['contact_telephone'] == null ? undefined : json['contact_telephone'],
        'contactEmail': json['contact_email'] == null ? undefined : json['contact_email'],
        'sharePercentageType': json['share_percentage_type'] == null ? undefined : json['share_percentage_type'],
        'sharePercentageRateUnit': json['share_percentage_rate_unit'] == null ? undefined : json['share_percentage_rate_unit'],
        'insurerSharePercentageValue': json['insurer_share_percentage_value'] == null ? undefined : json['insurer_share_percentage_value'],
        'insurerClaimReference1': json['insurer_claim_reference1'] == null ? undefined : json['insurer_claim_reference1'],
        'insurerClaimReference2': json['insurer_claim_reference2'] == null ? undefined : json['insurer_claim_reference2'],
        'participantFunction': json['participant_function'] == null ? undefined : json['participant_function'],
        'managingAgentCode': json['managing_agent_code'] == null ? undefined : json['managing_agent_code'],
        'consortiumNumber': json['consortium_number'] == null ? undefined : json['consortium_number'],
        'claimLineNumber': json['claim_line_number'] == null ? undefined : json['claim_line_number'],
    };
}

export function ClaimTransactionInsurerCreateToJSON(value?: ClaimTransactionInsurerCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'party_agency': value['partyAgency'],
        'party_id': value['partyId'],
        'party_name': value['partyName'],
        'contact_name': value['contactName'],
        'contact_telephone': value['contactTelephone'],
        'contact_email': value['contactEmail'],
        'share_percentage_type': value['sharePercentageType'],
        'share_percentage_rate_unit': value['sharePercentageRateUnit'],
        'insurer_share_percentage_value': value['insurerSharePercentageValue'],
        'insurer_claim_reference1': value['insurerClaimReference1'],
        'insurer_claim_reference2': value['insurerClaimReference2'],
        'participant_function': value['participantFunction'],
        'managing_agent_code': value['managingAgentCode'],
        'consortium_number': value['consortiumNumber'],
        'claim_line_number': value['claimLineNumber'],
    };
}

