/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SyncDirection } from './SyncDirection';
import {
    SyncDirectionFromJSON,
    SyncDirectionFromJSONTyped,
    SyncDirectionToJSON,
} from './SyncDirection';
import type { SyncStatus } from './SyncStatus';
import {
    SyncStatusFromJSON,
    SyncStatusFromJSONTyped,
    SyncStatusToJSON,
} from './SyncStatus';

/**
 * 
 * @export
 * @interface ClaimDocumentExternalRefPatch
 */
export interface ClaimDocumentExternalRefPatch {
    /**
     * Optional reference to the ECF transaction
     * @type {string}
     * @memberof ClaimDocumentExternalRefPatch
     */
    transactionId?: string;
    /**
     * ECF transaction reference (TR)
     * @type {string}
     * @memberof ClaimDocumentExternalRefPatch
     */
    transactionReference?: string;
    /**
     * Document ID in the external system
     * @type {string}
     * @memberof ClaimDocumentExternalRefPatch
     */
    externalDocumentId?: string;
    /**
     * Version in the external system
     * @type {string}
     * @memberof ClaimDocumentExternalRefPatch
     */
    externalVersion?: string;
    /**
     * Document type in the external system
     * @type {string}
     * @memberof ClaimDocumentExternalRefPatch
     */
    externalDocumentType?: string;
    /**
     * 
     * @type {SyncStatus}
     * @memberof ClaimDocumentExternalRefPatch
     */
    syncStatus?: SyncStatus;
    /**
     * 
     * @type {SyncDirection}
     * @memberof ClaimDocumentExternalRefPatch
     */
    syncDirection?: SyncDirection;
    /**
     * Additional metadata about the synchronization
     * @type {object}
     * @memberof ClaimDocumentExternalRefPatch
     */
    syncMetadata?: object;
    /**
     * Timestamp of the last synchronization attempt
     * @type {Date}
     * @memberof ClaimDocumentExternalRefPatch
     */
    lastSyncAt?: Date;
    /**
     * Error message if synchronization failed
     * @type {string}
     * @memberof ClaimDocumentExternalRefPatch
     */
    syncError?: string;
}

/**
 * Check if a given object implements the ClaimDocumentExternalRefPatch interface.
 */
export function instanceOfClaimDocumentExternalRefPatch(value: object): boolean {
    return true;
}

export function ClaimDocumentExternalRefPatchFromJSON(json: any): ClaimDocumentExternalRefPatch {
    return ClaimDocumentExternalRefPatchFromJSONTyped(json, false);
}

export function ClaimDocumentExternalRefPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimDocumentExternalRefPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'transactionId': json['transaction_id'] == null ? undefined : json['transaction_id'],
        'transactionReference': json['transaction_reference'] == null ? undefined : json['transaction_reference'],
        'externalDocumentId': json['external_document_id'] == null ? undefined : json['external_document_id'],
        'externalVersion': json['external_version'] == null ? undefined : json['external_version'],
        'externalDocumentType': json['external_document_type'] == null ? undefined : json['external_document_type'],
        'syncStatus': json['sync_status'] == null ? undefined : SyncStatusFromJSON(json['sync_status']),
        'syncDirection': json['sync_direction'] == null ? undefined : SyncDirectionFromJSON(json['sync_direction']),
        'syncMetadata': json['sync_metadata'] == null ? undefined : json['sync_metadata'],
        'lastSyncAt': json['last_sync_at'] == null ? undefined : (new Date(json['last_sync_at'])),
        'syncError': json['sync_error'] == null ? undefined : json['sync_error'],
    };
}

export function ClaimDocumentExternalRefPatchToJSON(value?: ClaimDocumentExternalRefPatch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'transaction_id': value['transactionId'],
        'transaction_reference': value['transactionReference'],
        'external_document_id': value['externalDocumentId'],
        'external_version': value['externalVersion'],
        'external_document_type': value['externalDocumentType'],
        'sync_status': SyncStatusToJSON(value['syncStatus']),
        'sync_direction': SyncDirectionToJSON(value['syncDirection']),
        'sync_metadata': value['syncMetadata'],
        'last_sync_at': value['lastSyncAt'] == null ? undefined : ((value['lastSyncAt'] as any).toISOString()),
        'sync_error': value['syncError'],
    };
}

