/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Source system for the document
 * @export
 */
export const DocumentSource = {
    Parsyl: 'parsyl',
    Imr: 'imr'
} as const;
export type DocumentSource = typeof DocumentSource[keyof typeof DocumentSource];


export function instanceOfDocumentSource(value: any): boolean {
    return Object.values(DocumentSource).includes(value);
}

export function DocumentSourceFromJSON(json: any): DocumentSource {
    return DocumentSourceFromJSONTyped(json, false);
}

export function DocumentSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentSource {
    return json as DocumentSource;
}

export function DocumentSourceToJSON(value?: DocumentSource | null): any {
    return value as any;
}

