/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Contact information of the person responding to the claim transaction
 * @export
 * @interface ECFClaimResponseResponderContact
 */
export interface ECFClaimResponseResponderContact {
    /**
     * 
     * @type {string}
     * @memberof ECFClaimResponseResponderContact
     */
    personName?: string;
    /**
     * 
     * @type {string}
     * @memberof ECFClaimResponseResponderContact
     */
    telephone?: string;
    /**
     * 
     * @type {string}
     * @memberof ECFClaimResponseResponderContact
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ECFClaimResponseResponderContact
     */
    fax?: string;
    /**
     * 
     * @type {string}
     * @memberof ECFClaimResponseResponderContact
     */
    classUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof ECFClaimResponseResponderContact
     */
    accountCode?: string;
}

/**
 * Check if a given object implements the ECFClaimResponseResponderContact interface.
 */
export function instanceOfECFClaimResponseResponderContact(value: object): boolean {
    return true;
}

export function ECFClaimResponseResponderContactFromJSON(json: any): ECFClaimResponseResponderContact {
    return ECFClaimResponseResponderContactFromJSONTyped(json, false);
}

export function ECFClaimResponseResponderContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): ECFClaimResponseResponderContact {
    if (json == null) {
        return json;
    }
    return {
        
        'personName': json['PersonName'] == null ? undefined : json['PersonName'],
        'telephone': json['Telephone'] == null ? undefined : json['Telephone'],
        'email': json['Email'] == null ? undefined : json['Email'],
        'fax': json['Fax'] == null ? undefined : json['Fax'],
        'classUserId': json['ClassUserId'] == null ? undefined : json['ClassUserId'],
        'accountCode': json['AccountCode'] == null ? undefined : json['AccountCode'],
    };
}

export function ECFClaimResponseResponderContactToJSON(value?: ECFClaimResponseResponderContact | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'PersonName': value['personName'],
        'Telephone': value['telephone'],
        'Email': value['email'],
        'Fax': value['fax'],
        'ClassUserId': value['classUserId'],
        'AccountCode': value['accountCode'],
    };
}

