/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ECFClaimRetrieve
 */
export interface ECFClaimRetrieve {
    /**
     * UMR - Unique Market Reference
     * @type {string}
     * @memberof ECFClaimRetrieve
     */
    brokerPolicyReference: string;
    /**
     * UCR - Unique Claim Reference
     * @type {string}
     * @memberof ECFClaimRetrieve
     */
    brokerClaimReference: string;
    /**
     * Claim line number in CLASS (needed for non-uniqueness of Company/Syndicate participation)
     * @type {number}
     * @memberof ECFClaimRetrieve
     */
    claimLineNumber: number;
    /**
     * Type of claim: 000, 001, 002, 003
     * @type {string}
     * @memberof ECFClaimRetrieve
     */
    claimType: string;
    /**
     * TR - Transaction Reference (optional)
     * @type {string}
     * @memberof ECFClaimRetrieve
     */
    transactionReference?: string;
}

/**
 * Check if a given object implements the ECFClaimRetrieve interface.
 */
export function instanceOfECFClaimRetrieve(value: object): boolean {
    if (!('brokerPolicyReference' in value)) return false;
    if (!('brokerClaimReference' in value)) return false;
    if (!('claimLineNumber' in value)) return false;
    if (!('claimType' in value)) return false;
    return true;
}

export function ECFClaimRetrieveFromJSON(json: any): ECFClaimRetrieve {
    return ECFClaimRetrieveFromJSONTyped(json, false);
}

export function ECFClaimRetrieveFromJSONTyped(json: any, ignoreDiscriminator: boolean): ECFClaimRetrieve {
    if (json == null) {
        return json;
    }
    return {
        
        'brokerPolicyReference': json['brokerPolicyReference'],
        'brokerClaimReference': json['brokerClaimReference'],
        'claimLineNumber': json['ClaimLineNumber'],
        'claimType': json['ClaimType'],
        'transactionReference': json['transactionReference'] == null ? undefined : json['transactionReference'],
    };
}

export function ECFClaimRetrieveToJSON(value?: ECFClaimRetrieve | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'brokerPolicyReference': value['brokerPolicyReference'],
        'brokerClaimReference': value['brokerClaimReference'],
        'ClaimLineNumber': value['claimLineNumber'],
        'ClaimType': value['claimType'],
        'transactionReference': value['transactionReference'],
    };
}

