/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ECFClaimResponseClaimResponseLeadResponseLeadContact } from './ECFClaimResponseClaimResponseLeadResponseLeadContact';
import {
    ECFClaimResponseClaimResponseLeadResponseLeadContactFromJSON,
    ECFClaimResponseClaimResponseLeadResponseLeadContactFromJSONTyped,
    ECFClaimResponseClaimResponseLeadResponseLeadContactToJSON,
} from './ECFClaimResponseClaimResponseLeadResponseLeadContact';
import type { ECFClaimResponseClaimResponseLeadResponseLloydsLead } from './ECFClaimResponseClaimResponseLeadResponseLloydsLead';
import {
    ECFClaimResponseClaimResponseLeadResponseLloydsLeadFromJSON,
    ECFClaimResponseClaimResponseLeadResponseLloydsLeadFromJSONTyped,
    ECFClaimResponseClaimResponseLeadResponseLloydsLeadToJSON,
} from './ECFClaimResponseClaimResponseLeadResponseLloydsLead';

/**
 * 
 * @export
 * @interface ECFClaimResponseClaimResponseLeadResponse
 */
export interface ECFClaimResponseClaimResponseLeadResponse {
    /**
     * 
     * @type {ECFClaimResponseClaimResponseLeadResponseLeadContact}
     * @memberof ECFClaimResponseClaimResponseLeadResponse
     */
    leadContact?: ECFClaimResponseClaimResponseLeadResponseLeadContact;
    /**
     * 
     * @type {ECFClaimResponseClaimResponseLeadResponseLloydsLead}
     * @memberof ECFClaimResponseClaimResponseLeadResponse
     */
    lloydsLead?: ECFClaimResponseClaimResponseLeadResponseLloydsLead;
}

/**
 * Check if a given object implements the ECFClaimResponseClaimResponseLeadResponse interface.
 */
export function instanceOfECFClaimResponseClaimResponseLeadResponse(value: object): boolean {
    return true;
}

export function ECFClaimResponseClaimResponseLeadResponseFromJSON(json: any): ECFClaimResponseClaimResponseLeadResponse {
    return ECFClaimResponseClaimResponseLeadResponseFromJSONTyped(json, false);
}

export function ECFClaimResponseClaimResponseLeadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ECFClaimResponseClaimResponseLeadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'leadContact': json['LeadContact'] == null ? undefined : ECFClaimResponseClaimResponseLeadResponseLeadContactFromJSON(json['LeadContact']),
        'lloydsLead': json['LloydsLead'] == null ? undefined : ECFClaimResponseClaimResponseLeadResponseLloydsLeadFromJSON(json['LloydsLead']),
    };
}

export function ECFClaimResponseClaimResponseLeadResponseToJSON(value?: ECFClaimResponseClaimResponseLeadResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'LeadContact': ECFClaimResponseClaimResponseLeadResponseLeadContactToJSON(value['leadContact']),
        'LloydsLead': ECFClaimResponseClaimResponseLeadResponseLloydsLeadToJSON(value['lloydsLead']),
    };
}

