/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ECFClaimResponseClaimResponseLeadResponseLloydsLead
 */
export interface ECFClaimResponseClaimResponseLeadResponseLloydsLead {
    /**
     * 
     * @type {string}
     * @memberof ECFClaimResponseClaimResponseLeadResponseLloydsLead
     */
    lloydsResponse?: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof ECFClaimResponseClaimResponseLeadResponseLloydsLead
     */
    privateComments?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof ECFClaimResponseClaimResponseLeadResponseLloydsLead
     */
    publicComments?: Array<object>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ECFClaimResponseClaimResponseLeadResponseLloydsLead
     */
    queryReason?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ECFClaimResponseClaimResponseLeadResponseLloydsLead
     */
    outstandingAmountQualifier?: string;
    /**
     * 
     * @type {string}
     * @memberof ECFClaimResponseClaimResponseLeadResponseLloydsLead
     */
    causeOfLoss?: string;
}

/**
 * Check if a given object implements the ECFClaimResponseClaimResponseLeadResponseLloydsLead interface.
 */
export function instanceOfECFClaimResponseClaimResponseLeadResponseLloydsLead(value: object): boolean {
    return true;
}

export function ECFClaimResponseClaimResponseLeadResponseLloydsLeadFromJSON(json: any): ECFClaimResponseClaimResponseLeadResponseLloydsLead {
    return ECFClaimResponseClaimResponseLeadResponseLloydsLeadFromJSONTyped(json, false);
}

export function ECFClaimResponseClaimResponseLeadResponseLloydsLeadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ECFClaimResponseClaimResponseLeadResponseLloydsLead {
    if (json == null) {
        return json;
    }
    return {
        
        'lloydsResponse': json['LloydsResponse'] == null ? undefined : json['LloydsResponse'],
        'privateComments': json['PrivateComments'] == null ? undefined : json['PrivateComments'],
        'publicComments': json['PublicComments'] == null ? undefined : json['PublicComments'],
        'queryReason': json['QueryReason'] == null ? undefined : json['QueryReason'],
        'outstandingAmountQualifier': json['OutstandingAmountQualifier'] == null ? undefined : json['OutstandingAmountQualifier'],
        'causeOfLoss': json['CauseOfLoss'] == null ? undefined : json['CauseOfLoss'],
    };
}

export function ECFClaimResponseClaimResponseLeadResponseLloydsLeadToJSON(value?: ECFClaimResponseClaimResponseLeadResponseLloydsLead | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'LloydsResponse': value['lloydsResponse'],
        'PrivateComments': value['privateComments'],
        'PublicComments': value['publicComments'],
        'QueryReason': value['queryReason'],
        'OutstandingAmountQualifier': value['outstandingAmountQualifier'],
        'CauseOfLoss': value['causeOfLoss'],
    };
}

