/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ECFClaimResponseClaimResponseLeadResponse } from './ECFClaimResponseClaimResponseLeadResponse';
import {
    ECFClaimResponseClaimResponseLeadResponseFromJSON,
    ECFClaimResponseClaimResponseLeadResponseFromJSONTyped,
    ECFClaimResponseClaimResponseLeadResponseToJSON,
} from './ECFClaimResponseClaimResponseLeadResponse';

/**
 * Detailed claim response information
 * @export
 * @interface ECFClaimResponseClaimResponse
 */
export interface ECFClaimResponseClaimResponse {
    /**
     * 
     * @type {string}
     * @memberof ECFClaimResponseClaimResponse
     */
    participantFunction?: string;
    /**
     * 
     * @type {string}
     * @memberof ECFClaimResponseClaimResponse
     */
    claimLineNo?: string;
    /**
     * 
     * @type {ECFClaimResponseClaimResponseLeadResponse}
     * @memberof ECFClaimResponseClaimResponse
     */
    leadResponse?: ECFClaimResponseClaimResponseLeadResponse;
}

/**
 * Check if a given object implements the ECFClaimResponseClaimResponse interface.
 */
export function instanceOfECFClaimResponseClaimResponse(value: object): boolean {
    return true;
}

export function ECFClaimResponseClaimResponseFromJSON(json: any): ECFClaimResponseClaimResponse {
    return ECFClaimResponseClaimResponseFromJSONTyped(json, false);
}

export function ECFClaimResponseClaimResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ECFClaimResponseClaimResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'participantFunction': json['ParticipantFunction'] == null ? undefined : json['ParticipantFunction'],
        'claimLineNo': json['ClaimLineNo'] == null ? undefined : json['ClaimLineNo'],
        'leadResponse': json['LeadResponse'] == null ? undefined : ECFClaimResponseClaimResponseLeadResponseFromJSON(json['LeadResponse']),
    };
}

export function ECFClaimResponseClaimResponseToJSON(value?: ECFClaimResponseClaimResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ParticipantFunction': value['participantFunction'],
        'ClaimLineNo': value['claimLineNo'],
        'LeadResponse': ECFClaimResponseClaimResponseLeadResponseToJSON(value['leadResponse']),
    };
}

