/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Claim entry details
 * @export
 * @interface ECFClaimResponseClaimEntry
 */
export interface ECFClaimResponseClaimEntry {
    /**
     * 
     * @type {string}
     * @memberof ECFClaimResponseClaimEntry
     */
    brokerReference?: string;
}

/**
 * Check if a given object implements the ECFClaimResponseClaimEntry interface.
 */
export function instanceOfECFClaimResponseClaimEntry(value: object): boolean {
    return true;
}

export function ECFClaimResponseClaimEntryFromJSON(json: any): ECFClaimResponseClaimEntry {
    return ECFClaimResponseClaimEntryFromJSONTyped(json, false);
}

export function ECFClaimResponseClaimEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ECFClaimResponseClaimEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'brokerReference': json['BrokerReference'] == null ? undefined : json['BrokerReference'],
    };
}

export function ECFClaimResponseClaimEntryToJSON(value?: ECFClaimResponseClaimEntry | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'BrokerReference': value['brokerReference'],
    };
}

