/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ECFDocumentSearchSearchCriteria
 */
export interface ECFDocumentSearchSearchCriteria {
    /**
     * Maximum number of results to be returned - 0 means no limit
     * @type {string}
     * @memberof ECFDocumentSearchSearchCriteria
     */
    searchLimit: string;
    /**
     * In conjunction with SearchLimit, support pagination (e.g., 'Next 100' with value 101) - 0 = start from first
     * @type {string}
     * @memberof ECFDocumentSearchSearchCriteria
     */
    searchStart: string;
    /**
     * Start date and time limit to be applied against DocumentVersionDtTime
     * @type {Date}
     * @memberof ECFDocumentSearchSearchCriteria
     */
    searchStartDtTime?: Date;
    /**
     * End date and time limit to be applied against DocumentVersionDtTime
     * @type {Date}
     * @memberof ECFDocumentSearchSearchCriteria
     */
    searchEndDtTime?: Date;
    /**
     * List of all document types to be searched, separated by blanks
     * @type {string}
     * @memberof ECFDocumentSearchSearchCriteria
     */
    documentTypeList?: string;
}

/**
 * Check if a given object implements the ECFDocumentSearchSearchCriteria interface.
 */
export function instanceOfECFDocumentSearchSearchCriteria(value: object): boolean {
    if (!('searchLimit' in value)) return false;
    if (!('searchStart' in value)) return false;
    return true;
}

export function ECFDocumentSearchSearchCriteriaFromJSON(json: any): ECFDocumentSearchSearchCriteria {
    return ECFDocumentSearchSearchCriteriaFromJSONTyped(json, false);
}

export function ECFDocumentSearchSearchCriteriaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ECFDocumentSearchSearchCriteria {
    if (json == null) {
        return json;
    }
    return {
        
        'searchLimit': json['SearchLimit'],
        'searchStart': json['SearchStart'],
        'searchStartDtTime': json['SearchStartDtTime'] == null ? undefined : (new Date(json['SearchStartDtTime'])),
        'searchEndDtTime': json['SearchEndDtTime'] == null ? undefined : (new Date(json['SearchEndDtTime'])),
        'documentTypeList': json['DocumentTypeList'] == null ? undefined : json['DocumentTypeList'],
    };
}

export function ECFDocumentSearchSearchCriteriaToJSON(value?: ECFDocumentSearchSearchCriteria | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'SearchLimit': value['searchLimit'],
        'SearchStart': value['searchStart'],
        'SearchStartDtTime': value['searchStartDtTime'] == null ? undefined : ((value['searchStartDtTime']).toISOString()),
        'SearchEndDtTime': value['searchEndDtTime'] == null ? undefined : ((value['searchEndDtTime']).toISOString()),
        'DocumentTypeList': value['documentTypeList'],
    };
}

