/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ECFResponse
 */
export interface ECFResponse {
    /**
     * SQS message ID returned from queuing the ECF request
     * @type {string}
     * @memberof ECFResponse
     */
    sqsMessageId: string;
    /**
     * Status of the request (e.g., 'queued')
     * @type {string}
     * @memberof ECFResponse
     */
    status: string;
}

/**
 * Check if a given object implements the ECFResponse interface.
 */
export function instanceOfECFResponse(value: object): boolean {
    if (!('sqsMessageId' in value)) return false;
    if (!('status' in value)) return false;
    return true;
}

export function ECFResponseFromJSON(json: any): ECFResponse {
    return ECFResponseFromJSONTyped(json, false);
}

export function ECFResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ECFResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'sqsMessageId': json['sqs_message_id'],
        'status': json['status'],
    };
}

export function ECFResponseToJSON(value?: ECFResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sqs_message_id': value['sqsMessageId'],
        'status': value['status'],
    };
}

