/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailSummaryCreate
 */
export interface EmailSummaryCreate {
    /**
     * Email thread identifier
     * @type {string}
     * @memberof EmailSummaryCreate
     */
    threadId: string;
    /**
     * LLM-generated summary of the email
     * @type {string}
     * @memberof EmailSummaryCreate
     */
    summaryText: string;
    /**
     * JSON blob of interesting properties extracted from the email
     * @type {object}
     * @memberof EmailSummaryCreate
     */
    identifierBlob?: object;
    /**
     * Processing status of the email summary (optional, defaults to 'pending')
     * @type {string}
     * @memberof EmailSummaryCreate
     */
    status?: EmailSummaryCreateStatusEnum;
}


/**
 * @export
 */
export const EmailSummaryCreateStatusEnum = {
    Pending: 'pending',
    Failed: 'failed',
    Complete: 'complete'
} as const;
export type EmailSummaryCreateStatusEnum = typeof EmailSummaryCreateStatusEnum[keyof typeof EmailSummaryCreateStatusEnum];


/**
 * Check if a given object implements the EmailSummaryCreate interface.
 */
export function instanceOfEmailSummaryCreate(value: object): boolean {
    if (!('threadId' in value)) return false;
    if (!('summaryText' in value)) return false;
    return true;
}

export function EmailSummaryCreateFromJSON(json: any): EmailSummaryCreate {
    return EmailSummaryCreateFromJSONTyped(json, false);
}

export function EmailSummaryCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailSummaryCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'threadId': json['thread_id'],
        'summaryText': json['summary_text'],
        'identifierBlob': json['identifier_blob'] == null ? undefined : json['identifier_blob'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function EmailSummaryCreateToJSON(value?: EmailSummaryCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'thread_id': value['threadId'],
        'summary_text': value['summaryText'],
        'identifier_blob': value['identifierBlob'],
        'status': value['status'],
    };
}

