/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailSummary
 */
export interface EmailSummary {
    /**
     * Unique internal ID for the email summary
     * @type {string}
     * @memberof EmailSummary
     */
    id: string;
    /**
     * Email thread identifier
     * @type {string}
     * @memberof EmailSummary
     */
    threadId: string;
    /**
     * LLM-generated summary of the email
     * @type {string}
     * @memberof EmailSummary
     */
    summaryText: string;
    /**
     * JSON blob of interesting properties extracted from the email
     * @type {object}
     * @memberof EmailSummary
     */
    identifierBlob?: object;
    /**
     * Processing status of the email summary
     * @type {string}
     * @memberof EmailSummary
     */
    status: EmailSummaryStatusEnum;
    /**
     * Timestamp when the email summary was created
     * @type {Date}
     * @memberof EmailSummary
     */
    createdAt: Date;
    /**
     * Timestamp when the email summary was last updated
     * @type {Date}
     * @memberof EmailSummary
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const EmailSummaryStatusEnum = {
    Pending: 'pending',
    Failed: 'failed',
    Complete: 'complete'
} as const;
export type EmailSummaryStatusEnum = typeof EmailSummaryStatusEnum[keyof typeof EmailSummaryStatusEnum];


/**
 * Check if a given object implements the EmailSummary interface.
 */
export function instanceOfEmailSummary(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('threadId' in value)) return false;
    if (!('summaryText' in value)) return false;
    if (!('status' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('updatedAt' in value)) return false;
    return true;
}

export function EmailSummaryFromJSON(json: any): EmailSummary {
    return EmailSummaryFromJSONTyped(json, false);
}

export function EmailSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'threadId': json['thread_id'],
        'summaryText': json['summary_text'],
        'identifierBlob': json['identifier_blob'] == null ? undefined : json['identifier_blob'],
        'status': json['status'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function EmailSummaryToJSON(value?: EmailSummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'thread_id': value['threadId'],
        'summary_text': value['summaryText'],
        'identifier_blob': value['identifierBlob'],
        'status': value['status'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

