/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailSummaryUpdate
 */
export interface EmailSummaryUpdate {
    /**
     * Email thread identifier
     * @type {string}
     * @memberof EmailSummaryUpdate
     */
    threadId?: string;
    /**
     * LLM-generated summary of the email
     * @type {string}
     * @memberof EmailSummaryUpdate
     */
    summaryText?: string;
    /**
     * JSON blob of interesting properties extracted from the email
     * @type {object}
     * @memberof EmailSummaryUpdate
     */
    identifierBlob?: object;
    /**
     * Processing status of the email summary
     * @type {string}
     * @memberof EmailSummaryUpdate
     */
    status?: EmailSummaryUpdateStatusEnum;
}


/**
 * @export
 */
export const EmailSummaryUpdateStatusEnum = {
    Pending: 'pending',
    Failed: 'failed',
    Complete: 'complete'
} as const;
export type EmailSummaryUpdateStatusEnum = typeof EmailSummaryUpdateStatusEnum[keyof typeof EmailSummaryUpdateStatusEnum];


/**
 * Check if a given object implements the EmailSummaryUpdate interface.
 */
export function instanceOfEmailSummaryUpdate(value: object): boolean {
    return true;
}

export function EmailSummaryUpdateFromJSON(json: any): EmailSummaryUpdate {
    return EmailSummaryUpdateFromJSONTyped(json, false);
}

export function EmailSummaryUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailSummaryUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'threadId': json['thread_id'] == null ? undefined : json['thread_id'],
        'summaryText': json['summary_text'] == null ? undefined : json['summary_text'],
        'identifierBlob': json['identifier_blob'] == null ? undefined : json['identifier_blob'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function EmailSummaryUpdateToJSON(value?: EmailSummaryUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'thread_id': value['threadId'],
        'summary_text': value['summaryText'],
        'identifier_blob': value['identifierBlob'],
        'status': value['status'],
    };
}

