/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClaimTransactionComment } from './ClaimTransactionComment';
import {
    ClaimTransactionCommentFromJSON,
    ClaimTransactionCommentFromJSONTyped,
    ClaimTransactionCommentToJSON,
} from './ClaimTransactionComment';
import type { PaginationInfo } from './PaginationInfo';
import {
    PaginationInfoFromJSON,
    PaginationInfoFromJSONTyped,
    PaginationInfoToJSON,
} from './PaginationInfo';

/**
 * 
 * @export
 * @interface GetAllTransactionComments200Response
 */
export interface GetAllTransactionComments200Response {
    /**
     * 
     * @type {Array<ClaimTransactionComment>}
     * @memberof GetAllTransactionComments200Response
     */
    data?: Array<ClaimTransactionComment>;
    /**
     * 
     * @type {PaginationInfo}
     * @memberof GetAllTransactionComments200Response
     */
    pagination?: PaginationInfo;
}

/**
 * Check if a given object implements the GetAllTransactionComments200Response interface.
 */
export function instanceOfGetAllTransactionComments200Response(value: object): boolean {
    return true;
}

export function GetAllTransactionComments200ResponseFromJSON(json: any): GetAllTransactionComments200Response {
    return GetAllTransactionComments200ResponseFromJSONTyped(json, false);
}

export function GetAllTransactionComments200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllTransactionComments200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ClaimTransactionCommentFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationInfoFromJSON(json['pagination']),
    };
}

export function GetAllTransactionComments200ResponseToJSON(value?: GetAllTransactionComments200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ClaimTransactionCommentToJSON)),
        'pagination': PaginationInfoToJSON(value['pagination']),
    };
}

