/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClaimTransactionContractMarket } from './ClaimTransactionContractMarket';
import {
    ClaimTransactionContractMarketFromJSON,
    ClaimTransactionContractMarketFromJSONTyped,
    ClaimTransactionContractMarketToJSON,
} from './ClaimTransactionContractMarket';
import type { PaginationInfo } from './PaginationInfo';
import {
    PaginationInfoFromJSON,
    PaginationInfoFromJSONTyped,
    PaginationInfoToJSON,
} from './PaginationInfo';

/**
 * 
 * @export
 * @interface GetAllContractMarkets200Response
 */
export interface GetAllContractMarkets200Response {
    /**
     * 
     * @type {Array<ClaimTransactionContractMarket>}
     * @memberof GetAllContractMarkets200Response
     */
    data: Array<ClaimTransactionContractMarket>;
    /**
     * 
     * @type {PaginationInfo}
     * @memberof GetAllContractMarkets200Response
     */
    pagination: PaginationInfo;
}

/**
 * Check if a given object implements the GetAllContractMarkets200Response interface.
 */
export function instanceOfGetAllContractMarkets200Response(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('pagination' in value)) return false;
    return true;
}

export function GetAllContractMarkets200ResponseFromJSON(json: any): GetAllContractMarkets200Response {
    return GetAllContractMarkets200ResponseFromJSONTyped(json, false);
}

export function GetAllContractMarkets200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllContractMarkets200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ClaimTransactionContractMarketFromJSON)),
        'pagination': PaginationInfoFromJSON(json['pagination']),
    };
}

export function GetAllContractMarkets200ResponseToJSON(value?: GetAllContractMarkets200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(ClaimTransactionContractMarketToJSON)),
        'pagination': PaginationInfoToJSON(value['pagination']),
    };
}

