/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClaimTransaction } from './ClaimTransaction';
import {
    ClaimTransactionFromJSON,
    ClaimTransactionFromJSONTyped,
    ClaimTransactionToJSON,
} from './ClaimTransaction';
import type { PaginationInfo } from './PaginationInfo';
import {
    PaginationInfoFromJSON,
    PaginationInfoFromJSONTyped,
    PaginationInfoToJSON,
} from './PaginationInfo';

/**
 * 
 * @export
 * @interface GetClaimTransactions200Response
 */
export interface GetClaimTransactions200Response {
    /**
     * 
     * @type {Array<ClaimTransaction>}
     * @memberof GetClaimTransactions200Response
     */
    data: Array<ClaimTransaction>;
    /**
     * 
     * @type {PaginationInfo}
     * @memberof GetClaimTransactions200Response
     */
    pagination: PaginationInfo;
}

/**
 * Check if a given object implements the GetClaimTransactions200Response interface.
 */
export function instanceOfGetClaimTransactions200Response(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('pagination' in value)) return false;
    return true;
}

export function GetClaimTransactions200ResponseFromJSON(json: any): GetClaimTransactions200Response {
    return GetClaimTransactions200ResponseFromJSONTyped(json, false);
}

export function GetClaimTransactions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetClaimTransactions200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ClaimTransactionFromJSON)),
        'pagination': PaginationInfoFromJSON(json['pagination']),
    };
}

export function GetClaimTransactions200ResponseToJSON(value?: GetClaimTransactions200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(ClaimTransactionToJSON)),
        'pagination': PaginationInfoToJSON(value['pagination']),
    };
}

