/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Claim } from './Claim';
import {
    ClaimFromJSON,
    ClaimFromJSONTyped,
    ClaimToJSON,
} from './Claim';
import type { PaginationInfo } from './PaginationInfo';
import {
    PaginationInfoFromJSON,
    PaginationInfoFromJSONTyped,
    PaginationInfoToJSON,
} from './PaginationInfo';

/**
 * 
 * @export
 * @interface GetClaims200Response
 */
export interface GetClaims200Response {
    /**
     * 
     * @type {Array<Claim>}
     * @memberof GetClaims200Response
     */
    data: Array<Claim>;
    /**
     * 
     * @type {PaginationInfo}
     * @memberof GetClaims200Response
     */
    pagination: PaginationInfo;
}

/**
 * Check if a given object implements the GetClaims200Response interface.
 */
export function instanceOfGetClaims200Response(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('pagination' in value)) return false;
    return true;
}

export function GetClaims200ResponseFromJSON(json: any): GetClaims200Response {
    return GetClaims200ResponseFromJSONTyped(json, false);
}

export function GetClaims200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetClaims200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ClaimFromJSON)),
        'pagination': PaginationInfoFromJSON(json['pagination']),
    };
}

export function GetClaims200ResponseToJSON(value?: GetClaims200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(ClaimToJSON)),
        'pagination': PaginationInfoToJSON(value['pagination']),
    };
}

