/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClaimDocumentExternalRef } from './ClaimDocumentExternalRef';
import {
    ClaimDocumentExternalRefFromJSON,
    ClaimDocumentExternalRefFromJSONTyped,
    ClaimDocumentExternalRefToJSON,
} from './ClaimDocumentExternalRef';
import type { PaginationInfo } from './PaginationInfo';
import {
    PaginationInfoFromJSON,
    PaginationInfoFromJSONTyped,
    PaginationInfoToJSON,
} from './PaginationInfo';

/**
 * 
 * @export
 * @interface GetDocumentExternalRefs200Response
 */
export interface GetDocumentExternalRefs200Response {
    /**
     * 
     * @type {Array<ClaimDocumentExternalRef>}
     * @memberof GetDocumentExternalRefs200Response
     */
    data: Array<ClaimDocumentExternalRef>;
    /**
     * 
     * @type {PaginationInfo}
     * @memberof GetDocumentExternalRefs200Response
     */
    pagination?: PaginationInfo;
}

/**
 * Check if a given object implements the GetDocumentExternalRefs200Response interface.
 */
export function instanceOfGetDocumentExternalRefs200Response(value: object): boolean {
    if (!('data' in value)) return false;
    return true;
}

export function GetDocumentExternalRefs200ResponseFromJSON(json: any): GetDocumentExternalRefs200Response {
    return GetDocumentExternalRefs200ResponseFromJSONTyped(json, false);
}

export function GetDocumentExternalRefs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDocumentExternalRefs200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ClaimDocumentExternalRefFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationInfoFromJSON(json['pagination']),
    };
}

export function GetDocumentExternalRefs200ResponseToJSON(value?: GetDocumentExternalRefs200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(ClaimDocumentExternalRefToJSON)),
        'pagination': PaginationInfoToJSON(value['pagination']),
    };
}

