/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailSummary } from './EmailSummary';
import {
    EmailSummaryFromJSON,
    EmailSummaryFromJSONTyped,
    EmailSummaryToJSON,
} from './EmailSummary';
import type { PaginationInfo } from './PaginationInfo';
import {
    PaginationInfoFromJSON,
    PaginationInfoFromJSONTyped,
    PaginationInfoToJSON,
} from './PaginationInfo';

/**
 * 
 * @export
 * @interface GetEmailSummaries200Response
 */
export interface GetEmailSummaries200Response {
    /**
     * 
     * @type {Array<EmailSummary>}
     * @memberof GetEmailSummaries200Response
     */
    data: Array<EmailSummary>;
    /**
     * 
     * @type {PaginationInfo}
     * @memberof GetEmailSummaries200Response
     */
    pagination: PaginationInfo;
}

/**
 * Check if a given object implements the GetEmailSummaries200Response interface.
 */
export function instanceOfGetEmailSummaries200Response(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('pagination' in value)) return false;
    return true;
}

export function GetEmailSummaries200ResponseFromJSON(json: any): GetEmailSummaries200Response {
    return GetEmailSummaries200ResponseFromJSONTyped(json, false);
}

export function GetEmailSummaries200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEmailSummaries200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(EmailSummaryFromJSON)),
        'pagination': PaginationInfoFromJSON(json['pagination']),
    };
}

export function GetEmailSummaries200ResponseToJSON(value?: GetEmailSummaries200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(EmailSummaryToJSON)),
        'pagination': PaginationInfoToJSON(value['pagination']),
    };
}

