/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClaimMovementAmountItem } from './ClaimMovementAmountItem';
import {
    ClaimMovementAmountItemFromJSON,
    ClaimMovementAmountItemFromJSONTyped,
    ClaimMovementAmountItemToJSON,
} from './ClaimMovementAmountItem';
import type { PaginationInfo } from './PaginationInfo';
import {
    PaginationInfoFromJSON,
    PaginationInfoFromJSONTyped,
    PaginationInfoToJSON,
} from './PaginationInfo';

/**
 * 
 * @export
 * @interface GetFinancialAmountItems200Response
 */
export interface GetFinancialAmountItems200Response {
    /**
     * 
     * @type {Array<ClaimMovementAmountItem>}
     * @memberof GetFinancialAmountItems200Response
     */
    data: Array<ClaimMovementAmountItem>;
    /**
     * 
     * @type {PaginationInfo}
     * @memberof GetFinancialAmountItems200Response
     */
    pagination: PaginationInfo;
}

/**
 * Check if a given object implements the GetFinancialAmountItems200Response interface.
 */
export function instanceOfGetFinancialAmountItems200Response(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('pagination' in value)) return false;
    return true;
}

export function GetFinancialAmountItems200ResponseFromJSON(json: any): GetFinancialAmountItems200Response {
    return GetFinancialAmountItems200ResponseFromJSONTyped(json, false);
}

export function GetFinancialAmountItems200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFinancialAmountItems200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ClaimMovementAmountItemFromJSON)),
        'pagination': PaginationInfoFromJSON(json['pagination']),
    };
}

export function GetFinancialAmountItems200ResponseToJSON(value?: GetFinancialAmountItems200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(ClaimMovementAmountItemToJSON)),
        'pagination': PaginationInfoToJSON(value['pagination']),
    };
}

