/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClaimTransactionFinancial } from './ClaimTransactionFinancial';
import {
    ClaimTransactionFinancialFromJSON,
    ClaimTransactionFinancialFromJSONTyped,
    ClaimTransactionFinancialToJSON,
} from './ClaimTransactionFinancial';
import type { PaginationInfo } from './PaginationInfo';
import {
    PaginationInfoFromJSON,
    PaginationInfoFromJSONTyped,
    PaginationInfoToJSON,
} from './PaginationInfo';

/**
 * 
 * @export
 * @interface ListAllTransactionFinancials200Response
 */
export interface ListAllTransactionFinancials200Response {
    /**
     * 
     * @type {Array<ClaimTransactionFinancial>}
     * @memberof ListAllTransactionFinancials200Response
     */
    data: Array<ClaimTransactionFinancial>;
    /**
     * 
     * @type {PaginationInfo}
     * @memberof ListAllTransactionFinancials200Response
     */
    pagination: PaginationInfo;
}

/**
 * Check if a given object implements the ListAllTransactionFinancials200Response interface.
 */
export function instanceOfListAllTransactionFinancials200Response(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('pagination' in value)) return false;
    return true;
}

export function ListAllTransactionFinancials200ResponseFromJSON(json: any): ListAllTransactionFinancials200Response {
    return ListAllTransactionFinancials200ResponseFromJSONTyped(json, false);
}

export function ListAllTransactionFinancials200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAllTransactionFinancials200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ClaimTransactionFinancialFromJSON)),
        'pagination': PaginationInfoFromJSON(json['pagination']),
    };
}

export function ListAllTransactionFinancials200ResponseToJSON(value?: ListAllTransactionFinancials200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(ClaimTransactionFinancialToJSON)),
        'pagination': PaginationInfoToJSON(value['pagination']),
    };
}

