/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * Error message
     * @type {string}
     * @memberof ModelError
     */
    error: string;
    /**
     * Error code
     * @type {string}
     * @memberof ModelError
     */
    code?: string;
    /**
     * Additional error details
     * @type {object}
     * @memberof ModelError
     */
    details?: object;
}

/**
 * Check if a given object implements the ModelError interface.
 */
export function instanceOfModelError(value: object): boolean {
    if (!('error' in value)) return false;
    return true;
}

export function ModelErrorFromJSON(json: any): ModelError {
    return ModelErrorFromJSONTyped(json, false);
}

export function ModelErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelError {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'code': json['code'] == null ? undefined : json['code'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function ModelErrorToJSON(value?: ModelError | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'error': value['error'],
        'code': value['code'],
        'details': value['details'],
    };
}

