/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationInfo
 */
export interface PaginationInfo {
    /**
     * Base64 encoded cursor for the current page
     * @type {string}
     * @memberof PaginationInfo
     */
    cursor?: string;
    /**
     * Base64 encoded cursor for the next page (null if no more pages)
     * @type {string}
     * @memberof PaginationInfo
     */
    nextCursor?: string;
    /**
     * Base64 encoded cursor for the previous page (null if first page)
     * @type {string}
     * @memberof PaginationInfo
     */
    prevCursor?: string;
    /**
     * Indicates if there are more pages available
     * @type {boolean}
     * @memberof PaginationInfo
     */
    hasMore: boolean;
    /**
     * Total number of items (only included if include_total=true)
     * @type {number}
     * @memberof PaginationInfo
     */
    total?: number;
}

/**
 * Check if a given object implements the PaginationInfo interface.
 */
export function instanceOfPaginationInfo(value: object): boolean {
    if (!('hasMore' in value)) return false;
    return true;
}

export function PaginationInfoFromJSON(json: any): PaginationInfo {
    return PaginationInfoFromJSONTyped(json, false);
}

export function PaginationInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
        'nextCursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
        'prevCursor': json['prev_cursor'] == null ? undefined : json['prev_cursor'],
        'hasMore': json['has_more'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function PaginationInfoToJSON(value?: PaginationInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'cursor': value['cursor'],
        'next_cursor': value['nextCursor'],
        'prev_cursor': value['prevCursor'],
        'has_more': value['hasMore'],
        'total': value['total'],
    };
}

