/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchEmailSummaryRequest
 */
export interface PatchEmailSummaryRequest {
    /**
     * Email thread identifier
     * @type {string}
     * @memberof PatchEmailSummaryRequest
     */
    threadId?: string;
    /**
     * LLM-generated summary of the email
     * @type {string}
     * @memberof PatchEmailSummaryRequest
     */
    summaryText?: string;
    /**
     * JSON blob of interesting properties extracted from the email
     * @type {object}
     * @memberof PatchEmailSummaryRequest
     */
    identifierBlob?: object;
}

/**
 * Check if a given object implements the PatchEmailSummaryRequest interface.
 */
export function instanceOfPatchEmailSummaryRequest(value: object): boolean {
    return true;
}

export function PatchEmailSummaryRequestFromJSON(json: any): PatchEmailSummaryRequest {
    return PatchEmailSummaryRequestFromJSONTyped(json, false);
}

export function PatchEmailSummaryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchEmailSummaryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'threadId': json['thread_id'] == null ? undefined : json['thread_id'],
        'summaryText': json['summary_text'] == null ? undefined : json['summary_text'],
        'identifierBlob': json['identifier_blob'] == null ? undefined : json['identifier_blob'],
    };
}

export function PatchEmailSummaryRequestToJSON(value?: PatchEmailSummaryRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'thread_id': value['threadId'],
        'summary_text': value['summaryText'],
        'identifier_blob': value['identifierBlob'],
    };
}

