/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The source system for the external reference
 * @export
 */
export const SourceSystem = {
    Imr: 'imr',
    Ecf: 'ecf',
    Parsyl: 'parsyl'
} as const;
export type SourceSystem = typeof SourceSystem[keyof typeof SourceSystem];


export function instanceOfSourceSystem(value: any): boolean {
    return Object.values(SourceSystem).includes(value);
}

export function SourceSystemFromJSON(json: any): SourceSystem {
    return SourceSystemFromJSONTyped(json, false);
}

export function SourceSystemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceSystem {
    return json as SourceSystem;
}

export function SourceSystemToJSON(value?: SourceSystem | null): any {
    return value as any;
}

