/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The synchronization status of the external reference
 * @export
 */
export const SyncStatus = {
    Pending: 'pending',
    PendingDownload: 'pending_download',
    PendingUpload: 'pending_upload',
    Downloaded: 'downloaded',
    Uploaded: 'uploaded',
    Failed: 'failed'
} as const;
export type SyncStatus = typeof SyncStatus[keyof typeof SyncStatus];


export function instanceOfSyncStatus(value: any): boolean {
    return Object.values(SyncStatus).includes(value);
}

export function SyncStatusFromJSON(json: any): SyncStatus {
    return SyncStatusFromJSONTyped(json, false);
}

export function SyncStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncStatus {
    return json as SyncStatus;
}

export function SyncStatusToJSON(value?: SyncStatus | null): any {
    return value as any;
}

