/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The direction of synchronization
 * @export
 */
export const SyncDirection = {
    Inbound: 'inbound',
    Outbound: 'outbound'
} as const;
export type SyncDirection = typeof SyncDirection[keyof typeof SyncDirection];


export function instanceOfSyncDirection(value: any): boolean {
    return Object.values(SyncDirection).includes(value);
}

export function SyncDirectionFromJSON(json: any): SyncDirection {
    return SyncDirectionFromJSONTyped(json, false);
}

export function SyncDirectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncDirection {
    return json as SyncDirection;
}

export function SyncDirectionToJSON(value?: SyncDirection | null): any {
    return value as any;
}

