/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationInfo } from './PaginationInfo';
import {
    PaginationInfoFromJSON,
    PaginationInfoFromJSONTyped,
    PaginationInfoToJSON,
} from './PaginationInfo';
import type { ThirdPartyEntity } from './ThirdPartyEntity';
import {
    ThirdPartyEntityFromJSON,
    ThirdPartyEntityFromJSONTyped,
    ThirdPartyEntityToJSON,
} from './ThirdPartyEntity';

/**
 * 
 * @export
 * @interface ThirdPartyEntitiesGet200Response
 */
export interface ThirdPartyEntitiesGet200Response {
    /**
     * 
     * @type {Array<ThirdPartyEntity>}
     * @memberof ThirdPartyEntitiesGet200Response
     */
    data: Array<ThirdPartyEntity>;
    /**
     * 
     * @type {PaginationInfo}
     * @memberof ThirdPartyEntitiesGet200Response
     */
    pagination: PaginationInfo;
}

/**
 * Check if a given object implements the ThirdPartyEntitiesGet200Response interface.
 */
export function instanceOfThirdPartyEntitiesGet200Response(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('pagination' in value)) return false;
    return true;
}

export function ThirdPartyEntitiesGet200ResponseFromJSON(json: any): ThirdPartyEntitiesGet200Response {
    return ThirdPartyEntitiesGet200ResponseFromJSONTyped(json, false);
}

export function ThirdPartyEntitiesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThirdPartyEntitiesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ThirdPartyEntityFromJSON)),
        'pagination': PaginationInfoFromJSON(json['pagination']),
    };
}

export function ThirdPartyEntitiesGet200ResponseToJSON(value?: ThirdPartyEntitiesGet200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(ThirdPartyEntityToJSON)),
        'pagination': PaginationInfoToJSON(value['pagination']),
    };
}

