/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThirdPartyEntityCreate
 */
export interface ThirdPartyEntityCreate {
    /**
     * ID of the associated claim
     * @type {string}
     * @memberof ThirdPartyEntityCreate
     */
    claimId: string;
    /**
     * Type of third party entity
     * @type {string}
     * @memberof ThirdPartyEntityCreate
     */
    entityType: ThirdPartyEntityCreateEntityTypeEnum;
    /**
     * Name of the third party entity
     * @type {string}
     * @memberof ThirdPartyEntityCreate
     */
    name?: string;
    /**
     * Reference identifier for the third party entity
     * @type {string}
     * @memberof ThirdPartyEntityCreate
     */
    reference?: string;
}


/**
 * @export
 */
export const ThirdPartyEntityCreateEntityTypeEnum = {
    Tpa: 'tpa',
    Adjuster: 'adjuster',
    Lawyer: 'lawyer'
} as const;
export type ThirdPartyEntityCreateEntityTypeEnum = typeof ThirdPartyEntityCreateEntityTypeEnum[keyof typeof ThirdPartyEntityCreateEntityTypeEnum];


/**
 * Check if a given object implements the ThirdPartyEntityCreate interface.
 */
export function instanceOfThirdPartyEntityCreate(value: object): boolean {
    if (!('claimId' in value)) return false;
    if (!('entityType' in value)) return false;
    return true;
}

export function ThirdPartyEntityCreateFromJSON(json: any): ThirdPartyEntityCreate {
    return ThirdPartyEntityCreateFromJSONTyped(json, false);
}

export function ThirdPartyEntityCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThirdPartyEntityCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'claimId': json['claim_id'],
        'entityType': json['entity_type'],
        'name': json['name'] == null ? undefined : json['name'],
        'reference': json['reference'] == null ? undefined : json['reference'],
    };
}

export function ThirdPartyEntityCreateToJSON(value?: ThirdPartyEntityCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'claim_id': value['claimId'],
        'entity_type': value['entityType'],
        'name': value['name'],
        'reference': value['reference'],
    };
}

