/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidationErrorsErrorsInner
 */
export interface ValidationErrorsErrorsInner {
    /**
     * Field name that failed validation
     * @type {string}
     * @memberof ValidationErrorsErrorsInner
     */
    field: string;
    /**
     * Validation error message
     * @type {string}
     * @memberof ValidationErrorsErrorsInner
     */
    message: string;
    /**
     * Validation error code
     * @type {string}
     * @memberof ValidationErrorsErrorsInner
     */
    code?: string;
}

/**
 * Check if a given object implements the ValidationErrorsErrorsInner interface.
 */
export function instanceOfValidationErrorsErrorsInner(value: object): boolean {
    if (!('field' in value)) return false;
    if (!('message' in value)) return false;
    return true;
}

export function ValidationErrorsErrorsInnerFromJSON(json: any): ValidationErrorsErrorsInner {
    return ValidationErrorsErrorsInnerFromJSONTyped(json, false);
}

export function ValidationErrorsErrorsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorsErrorsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'],
        'message': json['message'],
        'code': json['code'] == null ? undefined : json['code'],
    };
}

export function ValidationErrorsErrorsInnerToJSON(value?: ValidationErrorsErrorsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'field': value['field'],
        'message': value['message'],
        'code': value['code'],
    };
}

