/* tslint:disable */
/* eslint-disable */
/**
 * Claims API
 * API for managing insurance claims and ECF transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationErrorsErrorsInner } from './ValidationErrorsErrorsInner';
import {
    ValidationErrorsErrorsInnerFromJSON,
    ValidationErrorsErrorsInnerFromJSONTyped,
    ValidationErrorsErrorsInnerToJSON,
} from './ValidationErrorsErrorsInner';

/**
 * 
 * @export
 * @interface ValidationErrors
 */
export interface ValidationErrors {
    /**
     * 
     * @type {Array<ValidationErrorsErrorsInner>}
     * @memberof ValidationErrors
     */
    errors: Array<ValidationErrorsErrorsInner>;
    /**
     * General validation error message
     * @type {string}
     * @memberof ValidationErrors
     */
    message?: string;
}

/**
 * Check if a given object implements the ValidationErrors interface.
 */
export function instanceOfValidationErrors(value: object): boolean {
    if (!('errors' in value)) return false;
    return true;
}

export function ValidationErrorsFromJSON(json: any): ValidationErrors {
    return ValidationErrorsFromJSONTyped(json, false);
}

export function ValidationErrorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrors {
    if (json == null) {
        return json;
    }
    return {
        
        'errors': ((json['errors'] as Array<any>).map(ValidationErrorsErrorsInnerFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ValidationErrorsToJSON(value?: ValidationErrors | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'errors': ((value['errors'] as Array<any>).map(ValidationErrorsErrorsInnerToJSON)),
        'message': value['message'],
    };
}

